version: '3'
 
services:
 
    php:
        build:
            context: ./docker/php
        ports:
            - 9090:9000
        volumes:
            - ./:/srv/www/api
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
 
    nginx:
        image: renfaizal/wamp:nginx
        ports:
            - 8080:80
        volumes:
            - ./:/srv/www/api
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
 
    mysql:
        image: renfaizal/wamp:mysql
        ports:
            - 3306:3306
        depends_on:
            - php
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: toko_ol

            
